[app]
name = "browser"
target_platforms = ["android"]

[build]
type = "debug"

[package_name]
libffi = "https://github.com/libffi/libffi/releases/download/v3.5.2/libffi-3.5.2.tar.gz"
gradle-9.2.1 = "https://services.gradle.org/distributions/gradle-9.2.1-bin.zip"
browser = "https://github.com/kmedya-dev/test/archive/refs/tags/v19.tar.gz"
