name: Test File

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: searching
      run: |
        echo "Searching...."
        uname -a
        uname -i
        uname -m
        uname -n
        uname -o
        uname -r
        uname -s
        uname -v
